apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-uamk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-uamk
    app.kubernetes.io/part-of: ci1t-830-0034-app
  name: devfile-sample-uamk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-uamk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-uamk
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0034-tenant/ci1t-830-0034-app/devfile-sample-uamk@sha256:77d1f325a4cde90309c5c6df3742eecfc2972c427c6bad3cdb7f6f35b4ef0637
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
